/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        /* FlowZone Design System */
        bgBase: '#050507',
        bgElevated: '#0F0F14',
        bgOverlay: '#18181F',
        bgHover: '#22222C',
        brandGold: '#D4AF37',
        brandGoldBright: '#FFD700',
        brandBlue: '#00A8E8',
        brandBlueGlow: '#00D4FF',
        brandPurple: '#6C5CE7',
        brandCrimson: '#DC2626',
        textPrimary: '#F8F8FA',
        textSecondary: '#A1A1AA',
        textMuted: '#71717A',
        textInverse: '#050507',
        borderSubtle: '#2A2A35',
        borderActive: '#3E3E4F',
        tierWatch: '#6366F1',
        tierFlex: '#10B981',
        tierVetted: '#D4AF37',
        safeGreen: '#10B981',
        safeYellow: '#F59E0B',
        safeRed: '#DC2626',
        vibeSolid: '#00B4D8',
        vibeAngry: '#FF6B35',
        vibeGuarded: '#64748B',
        vibeStorm: '#7C3AED',
        charChallenger: '#DC2626',
        charNavigator: '#00A8E8',
        charAce: '#10B981',
        charNova: '#6C5CE7',
        /* v2 namespaced aliases — same colors, namespaced for clarity */
        fz: {
          base: '#050507',
          elevated: '#0F0F14',
          overlay: '#18181F',
          hover: '#22222C',
          border: '#2A2A35',
          gold: '#D4AF37',
          'gold-bright': '#FFD700',
          blue: '#00A8E8',
          'blue-glow': '#00D4FF',
          purple: '#6C5CE7',
          crimson: '#DC2626',
        },
        text: {
          primary: '#F8F8FA',
          secondary: '#A1A1AA',
          muted: '#71717A',
          inverse: '#050507',
        },
        tier: { watch: '#6366F1', flex: '#10B981', vetted: '#D4AF37' },
        safe: { green: '#10B981', yellow: '#F59E0B', red: '#DC2626' },
        vibe: { solid: '#00B4D8', angry: '#FF6B35', guarded: '#64748B', storm: '#7C3AED' },
        char: { challenger: '#DC2626', navigator: '#00A8E8', ace: '#10B981', nova: '#6C5CE7' },
      },
      fontFamily: {
        display: ["'Bebas Neue'", "sans-serif"],
        body: ["'Inter'", "sans-serif"],
        accent: ["'Permanent Marker'", "cursive"],
        mono: ["'JetBrains Mono'", "monospace"],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        'fz-sm': '4px',
        'fz-md': '8px',
        'fz-lg': '12px',
        'fz-xl': '16px',
        'fz-full': '9999px',
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        'fz-sm': '0 1px 2px rgba(0,0,0,0.3)',
        'fz-md': '0 4px 12px rgba(0,0,0,0.4)',
        'fz-lg': '0 8px 24px rgba(0,0,0,0.5)',
        'gold': '0 0 20px rgba(212,175,55,0.2)',
        'blue': '0 0 20px rgba(0,168,232,0.2)',
        'glow-gold': '0 0 30px rgba(212,175,55,0.3)',
        'glow-blue': '0 0 30px rgba(0,168,232,0.3)',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "pulse-gold": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(212,175,55,0.4)" },
          "50%": { boxShadow: "0 0 0 8px rgba(212,175,55,0)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-6px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "pulse-gold": "pulse-gold 2s ease-in-out infinite",
        "float": "float 3s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
